// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNpdkQVL5WMyn7dF0RF41bsk5G9gY2T1M',
    appId: '1:479669828392:web:3c021430540d70a4722e1d',
    messagingSenderId: '479669828392',
    projectId: 'yogaapp-1cb1c',
    authDomain: 'yogaapp-1cb1c.firebaseapp.com',
    storageBucket: 'yogaapp-1cb1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OTYlzyhy2tWyx1crtqU-3L91IcQa23E',
    appId: '1:479669828392:android:821218ffe89eecbd722e1d',
    messagingSenderId: '479669828392',
    projectId: 'yogaapp-1cb1c',
    storageBucket: 'yogaapp-1cb1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlff6ut7l1pzkfFVSuq7dSAcMGgaeyBZw',
    appId: '1:479669828392:ios:24dd1fd119b672a3722e1d',
    messagingSenderId: '479669828392',
    projectId: 'yogaapp-1cb1c',
    storageBucket: 'yogaapp-1cb1c.appspot.com',
    iosClientId: '479669828392-mjid72nddsfv9jhrpmp3aq3f5ol7fot0.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlff6ut7l1pzkfFVSuq7dSAcMGgaeyBZw',
    appId: '1:479669828392:ios:24dd1fd119b672a3722e1d',
    messagingSenderId: '479669828392',
    projectId: 'yogaapp-1cb1c',
    storageBucket: 'yogaapp-1cb1c.appspot.com',
    iosClientId: '479669828392-mjid72nddsfv9jhrpmp3aq3f5ol7fot0.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaApp',
  );
}
